---
title: "demo_dataframes"
author: "D Perret"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      prompt = FALSE,
                      error = TRUE,
                      message = FALSE,
                      cache = FALSE,
                      cache.lazy = FALSE,
                      eval = TRUE,
                      eval.after = "fig.cap")

library(tidyverse)
library(rFIA)
library(ggplot2)
library(ggExtra)
library(rgdal)
library(sp)
library(ggsci)
library(raster)
library(splines)
library(lme4)
library(patchwork)
library(performance)
library(ggeffects)
select <- dplyr::select

# setting my preferred ggplot2 theme
theme_set(theme_bw())
theme_update(text = element_text(size=16, color = "black"),
             panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(),
             strip.background = element_blank(),
             panel.border=element_rect(size=1.5))

# colors to be used in all map figures
mapcolor <- "wheat3"
linecolor <- "gray40"
regioncolors <- c("Cascade Mixed Forest" = "#009E73",
                  "Northern Rocky Mountain Forest-Steppe" = "#56B4E9",
                  "Middle Rocky Mountain Steppe" = "#E69F00",
                  "Southern Rocky Mountain Steppe" = "#CC79A7",
                  "zIntermountain Semi-Desert" = "gray20",
                  "AZ-NM Mountains" = "#D55E00")

# sourcing estimation base code
source("code/growMort_rewrite_METRIC.R")

```

# READ EXISTING DATAFRAMES

```{r}

ind.mort.dat <- read.csv("data/mortdat_2jul24.csv",header=T)
seed.dat <- read.csv("data/seeddat_2jul24.csv",header=T)
sap.dat <- read.csv("data/sapdat_2jul24.csv",header=T)

```


# INDIVIDUAL MORTALITY DATA

```{r}

ind.mort.dat <- all.fia$TREE %>% 
  filter(most.recent == "yes",
         PLT_CN%in%co.pres.plots,
         SPCD%in%c(19,93),
         #PREVDIA>5,
         PREV_STATUS_CD==1,
         STATUSCD%in%c(1,2),
         INVYR>2009) %>% 
  left_join(all.fia$TREE %>% 
              select(TRE_CN,
                     PREV_CR = CR,
                     PREV_HT = HT,
                     PREV_VOL = VOLCFGRS,
                     prev.insect.damage = insect.damage,
                     prev.disease.damage = disease.damage,
                     prev.other.damage = other.damage),
            by=c("PREV_TRE_CN"="TRE_CN")) %>% 
  select(TRE_CN,SPCD,PLT_CN,CONDID,
         PREV_STATUS_CD,STATUSCD, MORTYR,
         DIA,PREVDIA, PREV_HT, PREV_VOL,
         PREV_CR, 
         prev.insect.damage, prev.disease.damage, prev.other.damage,
         agent_key) %>% 
  mutate(SURV = ifelse(STATUSCD==2,0,STATUSCD),
         SPCD = factor(SPCD)) %>% 
  left_join(.,
            all.fia$PLOT %>% 
              select(PLT_CN,
                     contains("MAT"),
                     contains("MAP"),
                     contains("CMD"),
                     contains("MWMT"),
                     ECOSUBCD, contains("REMPER"),
                     INVYR, ELEV, most.recent,
                     MEASYEAR),
            by="PLT_CN") %>%
  left_join(mort.area.er %>% 
              mutate(area.fire.prop = area.fire/area.total,
                     area.id.prop = area.id/area.total),
            by="ECOSUBCD") %>% 
  left_join(plot.attributes.prev) %>% 
  left_join(dall.er.ablapien %>% 
              sf::st_drop_geometry() %>% 
              select(MAP_UNIT_S, quad.19, quad.93, mult.comp.coexist),
            by=c("ECOSUBCD" = "MAP_UNIT_S")) %>% 
  filter(!is.na(MAT_remper_mean),
         !is.na(MAT_ref_mean),
         !is.na(PREV_BAH)) %>% 
  left_join(co.cond,
            by = c("PLT_CN","CONDID")) %>% 
  mutate(
    prev.insect.damage = factor(prev.insect.damage),
    prev.disease.damage = factor(prev.disease.damage),
    prev.damage = (ifelse(prev.insect.damage==1 | prev.disease.damage==1, 1, 0)),
    T1 = MEASYEAR-round(REMPER),
    T2 = MEASYEAR)

```

# SEEDLING REGENERATION DATA

```{r}

# making a dataframe of plot-level presence/absence for seedlings of each species on plots that have co-occurring adults
seed <- data.frame(PLT_CN = rep(unique(ind.mort.dat$PLT_CN),each=2),
                   SPCD = c(19,93)) %>% 
  left_join(all.fia$SEEDLING %>% 
              filter(SPCD %in% c(19,93),
                     PLT_CN %in% co.pres.plots,
                     INVYR > 2009) %>% 
              select(PLT_CN,
                     SPCD,
                     CONDID,
                     TREECOUNT),
            by=c("PLT_CN","SPCD")) %>% 
  group_by(PLT_CN,SPCD) %>% 
  summarise(SEED.PRES = ifelse(sum(TREECOUNT > 0, na.rm=T), 1, 0)) %>% 
  ungroup()

# pulling conditions that contain microplots
micr.cond <- all.fia$COND %>% 
  filter(PLT_CN %in% seed$PLT_CN,
         INVYR>2009) %>% 
  summarise(fire = ifelse(DSTRBCD1 %in% 30:32 |
                            DSTRBCD2 %in% 30:32 |
                            DSTRBCD3 %in% 30:32, 
                          "burned", "unburned"),
            bda = ifelse(DSTRBCD1 %in% c(10:12,20:22) | 
                           DSTRBCD2 %in% c(10:12,20:22) | 
                           DSTRBCD3 %in% c(10:12,20:22),
                         "bda", "no.bda"),
            fire.year = case_when(DSTRBCD1 %in% 30:32 ~ DSTRBYR1,
                                  DSTRBCD2 %in% 30:32 ~ DSTRBYR2,
                                  DSTRBCD3 %in% 30:32 ~ DSTRBYR3),
            bda.year = case_when(DSTRBCD1 %in% c(10:12,20:22) ~ DSTRBYR1,
                                 DSTRBCD2 %in% c(10:12,20:22) ~ DSTRBYR2,
                                 DSTRBCD3 %in% c(10:12,20:22) ~ DSTRBYR3),
            disturbance = case_when(fire == "burned" & bda == "bda" ~ "fire/bda",
                                    fire == "burned" & bda == "no.bda" ~ "fire",
                                    fire == "unburned" & bda == "bda" ~ "bda",
                                    fire == "unburned" & bda == "no.bda" ~"undisturbed"),
            CONDID = CONDID,
            PLT_CN = PLT_CN,
            SLOPE = SLOPE,
            ASPECT = ASPECT,
            MICRPROP_UNADJ = MICRPROP_UNADJ) %>% 
  filter(MICRPROP_UNADJ>0) %>% 
  group_by(PLT_CN) %>% 
  filter(MICRPROP_UNADJ == max(MICRPROP_UNADJ)) %>% 
  filter(case_when(n()>1 ~ CONDID == min(CONDID),
                   n()==1 ~ !is.na(MICRPROP_UNADJ))) %>%
  ungroup()

# attempting a disturbance severity proxy
dist.sev <- ind.mort.dat %>% 
  mutate(MORT = STATUSCD-PREV_STATUS_CD) %>%
  group_by(PLT_CN,SPCD) %>% 
  summarise(mort.prop = sum(MORT)/n(),
            fire.sev = sum(MORT*ifelse(agent_key=="fire",1,0),na.rm=T)/n(),
            bda.sev = sum(MORT*ifelse(agent_key%in%c("disease","insect"),1,0),na.rm=T)/n(),
            dist.sev = sum(MORT*ifelse(agent_key%in%c("fire","disease","insect"),1,0),na.rm=T)/n())


# dataframe of plot-level presence/absence of seedlings, with condition-level disturbance information and plot-level climate information and ecoregion-level disturbance and population information
seed.dat <- seed %>% 
  left_join(.,
            all.fia$PLOT %>% 
              select(PLT_CN,
                     contains("MAT"),
                     contains("MAP"),
                     contains("CMD"),
                     #contains("EXT"),
                     #contains("EMT"),
                     contains("MWMT"),
                     contains("REMPER"),
                     ECOSUBCD,
                     mult.comp.coexist,
                     INVYR, ELEV, most.recent), # %>% 
              # mutate(MAT_anom = MAT_remper_mean-MAT_19802010,
              #        MAP_anom = MAP_remper_mean-MAP_19802010,
              #        CMD_anom = CMD_remper_mean-CMD_19802010,
              #        MAP_relanom = MAP_anom/MAP_19802010),
            by="PLT_CN") %>% 
  left_join(micr.cond,
            by=c("PLT_CN")) %>% 
  left_join(mort.area.er %>% 
              mutate(area.fire.prop = area.fire/area.total,
                     area.id.prop = area.id/area.total),
            by="ECOSUBCD") %>% 
  left_join(plot.attributes.prev, by = "PLT_CN") %>% 
  mutate(yr.since.fire = ifelse(fire == "burned",
                                INVYR-fire.year,
                                NA),
         yr.since.dist = case_when(disturbance == "fire" ~ INVYR - fire.year,
                                   disturbance == "fire/bda" ~ INVYR - fire.year,
                                   disturbance == "bda" ~ INVYR - bda.year,
                                   bda.year == 9999 ~ INVYR - INVYR),
         yr.since.fire = ifelse(is.na(yr.since.fire),
                                100, yr.since.fire),
         yr.since.dist = ifelse(is.na(yr.since.dist),
                                100, yr.since.dist),
         SPCD=factor(SPCD)) %>% 
  left_join(dist.sev,
            by=c("PLT_CN","SPCD")) %>% 
  mutate(fire.sev = ifelse(is.na(fire.sev),0,fire.sev),
         bda.sev = ifelse(is.na(bda.sev),0,bda.sev),
         dist.sev = ifelse(is.na(dist.sev),0,dist.sev),
         mort.prop = ifelse(is.na(mort.prop),0,mort.prop)) %>% 
  filter(!is.na(ASPECT),
         !is.na(MAT_ref_mean))


```

# SAPLING PRESENCE DATA

```{r}

sap <- data.frame(PLT_CN = rep(unique(ind.mort.dat$PLT_CN),each=2),
                  SPCD=c(19,93)) %>% 
  left_join(all.fia$TREE %>% 
              filter(SPCD %in% c(19,93),
                     DIA < 12.7,
                     STATUSCD==1,
                     is.na(PREV_TRE_CN),  # ONLY NEW SAPLINGS
                     PLT_CN %in% co.pres.plots,
                     INVYR > 2009) %>% 
              group_by(PLT_CN, SPCD) %>% 
              summarise(sap_count = n()),
            by = c("PLT_CN","SPCD")) %>% 
  mutate(SAP.COUNT = ifelse(is.na(sap_count),0,sap_count),
         SAP.PRES = ifelse(SAP.COUNT>0,1,SAP.COUNT))

sap.dat <- sap %>% 
  left_join(.,
            all.fia$PLOT %>% 
              select(PLT_CN,
                     contains("MAT"),
                     contains("MAP"),
                     contains("CMD"),
                     #contains("EXT"),
                     #contains("EMT"),
                     contains("MWMT"),
                     contains("REMPER"),
                     ECOSUBCD,
                     INVYR, ELEV, most.recent), # %>% 
              # mutate(MAT_anom = MAT_remper_mean-MAT_19802010,
              #        MAP_anom = MAP_remper_mean-MAP_19802010,
              #        CMD_anom = CMD_remper_mean-CMD_19802010,
              #        MAP_relanom = MAP_anom/MAP_19802010),
            by="PLT_CN") %>% 
  left_join(micr.cond,
            by=c("PLT_CN")) %>% 
  left_join(mort.area.er %>% 
              mutate(area.fire.prop = area.fire/area.total,
                     area.id.prop = area.id/area.total),
            by="ECOSUBCD") %>% 
  left_join(plot.attributes.prev, by = "PLT_CN") %>% 
  mutate(yr.since.fire = ifelse(fire == "burned",
                                INVYR-fire.year,
                                NA),
         yr.since.dist = case_when(disturbance == "fire" ~ INVYR - fire.year,
                                   disturbance == "fire/bda" ~ INVYR - fire.year,
                                   disturbance == "bda" ~ INVYR - bda.year,
                                   bda.year == 9999 ~ INVYR - INVYR),
         yr.since.fire = ifelse(is.na(yr.since.fire),
                                100, yr.since.fire),
         yr.since.dist = ifelse(is.na(yr.since.dist),
                                100, yr.since.dist),
         SPCD=factor(SPCD)) %>% 
  left_join(dist.sev,
            by=c("PLT_CN","SPCD")) %>% 
  mutate(fire.sev = ifelse(is.na(fire.sev),0,fire.sev),
         bda.sev = ifelse(is.na(bda.sev),0,bda.sev),
         dist.sev = ifelse(is.na(dist.sev),0,dist.sev),
         mort.prop = ifelse(is.na(mort.prop),0,mort.prop)) %>% 
  filter(!is.na(ASPECT),
         !is.na(MAT_ref_mean))


```

WRITING DATAFRAMES

```{r}

write.csv(ind.mort.dat,file="data/indmortdat_1may24.csv")
write.csv(seed.dat,file="data/seeddat_1may24.csv")
write.csv(sap.dat,file="data/sapdat_1may24.csv")


```

































